{
 "title": "Elasticsearch cluster",
 "panels": [
  {
   "title": "Cluster status",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "query": "SELECT max(\"status_code\") FROM \"elasticsearch_cluster_health\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes status",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "UP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"number_of_nodes\") FROM \"elasticsearch_cluster_health\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DOWN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"total_number_of_nodes\") - min(\"number_of_nodes\") FROM \"elasticsearch_cluster_health\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Elasticsearch shards",
 "panels": [
  {
   "title": "Active primary shards",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "query": "SELECT last(\"active_primary_shards\") FROM \"elasticsearch_cluster_health\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "query": "SELECT last(\"active_shards\") FROM \"elasticsearch_cluster_health\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "query": "SELECT last(\"initializing_shards\") FROM \"elasticsearch_cluster_health\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "query": "SELECT last(\"relocating_shards\") FROM \"elasticsearch_cluster_health\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "query": "SELECT max(\"unassigned_shards\") FROM \"elasticsearch_cluster_health\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Network metrics",
 "panels": [
  {
   "title": "Open transport connections",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_transport",
     "query": "SELECT max(\"server_open\") FROM \"elasticsearch_transport\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open http connections",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name.$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_http",
     "query": "SELECT max(\"current_open\") as \"open\" FROM \"elasticsearch_http\" WHERE (node_name =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transport size",
   "type": "graph",
   "description": "The Rx(receiving) and Tx(transmitting) package size",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_transport",
     "_comment": "In the query 'count(rx_size_in_bytes) / count(rx_size_in_bytes)' part is added to have 'null' results, because by default 'non_negative_derivative' function returns nothing if interval does not contain values.",
     "query": "SELECT non_negative_derivative(mean(\"rx_size_in_bytes\"), 1s) * count(\"rx_size_in_bytes\") / count(\"rx_size_in_bytes\") FROM \"elasticsearch_transport\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_transport",
     "_comment": "In the query 'count(tx_size_in_bytes) / count(tx_size_in_bytes)' part is added to have 'null' results, because by default 'non_negative_derivative' function returns nothing if interval does not contain values.",
     "query": "SELECT non_negative_derivative(mean(\"tx_size_in_bytes\"), 1s) * count(\"tx_size_in_bytes\") / count(\"tx_size_in_bytes\") FROM \"elasticsearch_transport\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "JVM heap and GC metrics",
 "panels": [
  {
   "title": "JVM heap usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "SELECT mean(\"mem_heap_used_in_bytes\") AS \"used\", mean(\"mem_heap_max_in_bytes\") AS \"total\" FROM \"elasticsearch_jvm\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM heap usage percent",
   "type": "graph",
   "description": "Elasticsearch is set up to initiate garbage collections whenever JVM heap usage hits 75 percent. As shown above, it may be useful to monitor which nodes exhibit high heap usage, and set up an alert to find out if any node is consistently using over 85 percent of heap memory; this indicates that the rate of garbage collection isn’t keeping up with the rate of garbage creation. To address this problem, you can either increase your heap size (as long as it remains below the recommended guidelines stated above), or scale out the cluster by adding more nodes.",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "SELECT mean(\"mem_heap_used_percent\") FROM \"elasticsearch_jvm\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM non heap usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "SELECT mean(\"mem_non_heap_used_in_bytes\") AS \"used\" FROM \"elasticsearch_jvm\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "description": "Time spent on major GCs that collect old generation objects and on minor GCs that collects young generation objects in JVM (time rate per sampling interval).",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "SELECT non_negative_difference(max(\"gc_collectors_old_collection_time_in_millis\")) * mean(\"gc_collectors_old_collection_time_in_millis\") / mean(\"gc_collectors_old_collection_time_in_millis\") AS \"old\", non_negative_difference(max(\"gc_collectors_young_collection_time_in_millis\")) * mean(\"gc_collectors_young_collection_time_in_millis\") / mean(\"gc_collectors_young_collection_time_in_millis\") AS \"young\" FROM \"elasticsearch_jvm\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Memory metrics",
 "panels": [
  {
   "title": "OS memory usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE (\"pod_name\" =~ /^$node_name$*/ AND \"type\" = 'pod' AND \"namespace_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_pod_name total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/limit",
     "query": "SELECT mean(\"value\") FROM \"memory/limit\" WHERE (\"pod_name\" =~ /^$node_name$*/ AND \"type\" = 'pod' AND \"namespace_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Disk metrics",
 "panels": [
  {
   "title": "Disk usage in percent",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host] used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_fs",
     "query": "SELECT 100 * (mean(\"total_total_in_bytes\") - mean(\"total_free_in_bytes\")) / mean(\"total_total_in_bytes\") FROM \"elasticsearch_fs\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" ,\"node_host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host] total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_fs",
     "query": "SELECT mean(\"total_total_in_bytes\") FROM \"elasticsearch_fs\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\", \"node_host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name [$tag_node_host] used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_fs",
     "query": "SELECT mean(\"total_total_in_bytes\") - mean( \"total_available_in_bytes\") FROM \"elasticsearch_fs\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY  time($__interval), \"node_name\", \"node_host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O operations",
   "type": "graph",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host] $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_fs",
     "_comment": "In the query 'count(io_stats_total_read_operations) / count(io_stats_total_read_operations)' part is added to have 'null' results, because by default 'non_negative_derivative' function returns nothing if interval does not contain values.",
     "query": "SELECT non_negative_derivative(mean(\"io_stats_total_read_operations\"), 1s) * count(\"io_stats_total_read_operations\") / count(\"io_stats_total_read_operations\") AS \"read\", non_negative_derivative(mean(\"io_stats_total_write_operations\"), 1s) AS \"write\" FROM \"elasticsearch_fs\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\", \"node_host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O usage",
   "type": "graph",
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host] $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "_comment": "In the query 'count(io_stats_total_read_kilobytes) / count(io_stats_total_read_kilobytes)' part is added to have 'null' results, because by default 'non_negative_derivative' function returns nothing if interval does not contain values.",
     "query": "SELECT non_negative_derivative(mean(\"io_stats_total_read_kilobytes\"), 1s) * count(\"io_stats_total_read_kilobytes\") / count(\"io_stats_total_read_kilobytes\") AS \"read\", non_negative_derivative(mean(\"io_stats_total_write_kilobytes\"), 1s) AS \"write\" FROM \"elasticsearch_fs\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\", \"node_host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "CPU metrics",
 "panels": [
  {
   "title": "CPU load average (5 min)",
   "type": "graph",
   "description": "Five-minute load average on the system",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_os",
     "query": "SELECT mean(\"cpu_load_average_5m\") FROM \"elasticsearch_os\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\", \"node_host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU load in percent",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_process",
     "query": "SELECT mean(\"cpu_percent\") FROM \"elasticsearch_process\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\", \"node_host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU load by pod",
   "type": "graph",
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE (\"pod_name\" =~ /^$node_name$*/ AND \"type\" = 'pod' AND \"namespace_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_pod_name total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT mean(\"value\") FROM \"cpu/limit\" WHERE (\"pod_name\" =~ /^$node_name$*/ AND \"type\" = 'pod' AND \"namespace_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Indices statistics",
 "panels": [
  {
   "title": "Indices total operations",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT  mean(flush_total) as \"flush\", mean(get_exists_total) as \"get-exists\", mean(get_missing_total) as \"get-missing\", mean(get_total) as \"get\", mean(indexing_delete_total) as \"indexing-delete\", mean(indexing_index_total) as \"indexing-index\", mean(indexing_noop_update_total) as \"indexing-noop-update\", mean(merges_total) as \"merges\", mean(percolate_total) as \"percolate\", mean(refresh_total) as \"refresh\", mean(search_fetch_total) as \"search-fetch\", mean(search_query_total) as \"search-query\", mean(search_scroll_total) as \"search-scroll\", mean(suggest_total) as \"suggest\", mean(warmer_total) as \"warmer\" FROM \"elasticsearch_indices\" WHERE (node_name =~ /$node_name/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), * fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices time operations",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(merges_total_time_in_millis) AS \"merges-total\", mean(flush_total_time_in_millis) AS \"flush-total\", mean(get_exists_time_in_millis) AS \"get-exists\", mean(get_missing_time_in_millis) AS \"get-missing\", mean(get_time_in_millis) AS \"get\", mean(indexing_delete_time_in_millis) AS \"indexing-delete\", mean(indexing_index_time_in_millis) AS \"indexing-index\", mean(indexing_throttle_time_in_millis) AS \"indexing-throttle\", mean(merges_total_stopped_time_in_millis) AS \"merges-total-stopped\", mean(merges_total_throttled_time_in_millis) AS \"merges-total-throttled\", mean(merges_total_time_in_millis) AS \"merges-total\", mean(percolate_time_in_millis) AS \"percolate\", mean(recovery_throttle_time_in_millis) AS \"recovery-throttle\", mean(refresh_total_time_in_millis) AS \"refresh-total\", mean(search_fetch_time_in_millis) AS \"search-fetch\", mean(search_query_time_in_millis) AS \"search-query\", mean(search_scroll_time_in_millis) AS \"search-scroll\", mean(store_throttle_time_in_millis) AS \"store-throttle\", mean(suggest_time_in_millis) AS \"suggest\", mean(warmer_total_time_in_millis) AS \"warmer-total\" FROM \"elasticsearch_indices\" WHERE (node_name =~ /$node_name/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), * fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices current operations",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT mean(\"get_current\") AS \"get\", mean(\"indexing_index_current\") AS \"index\", mean(\"search_fetch_current\") AS \"search fetch\", mean(\"search_query_current\") AS \"search query\" FROM \"elasticsearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices document count",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "document count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "query": "SELECT mean(\"docs_count\") FROM \"elasticsearch_clusterstats_indices\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval), \"cluster_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices data size",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "indices size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "query": "SELECT mean(\"store_size_in_bytes\") FROM \"elasticsearch_clusterstats_indices\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval), \"cluster_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Thread pool queues and requests metrics",
 "panels": [
  {
   "title": "Requests latency",
   "type": "graph",
   "description": "If you notice the indexing latency increasing, you may be trying to index too many documents at one time (Elasticsearch’s documentation recommends starting with a bulk indexing size of 5 to 15 megabytes and increasing slowly from there).\nIf you are planning to index a lot of documents and you don’t need the new information to be immediately available for search, you can optimize for indexing performance over search performance by decreasing refresh frequency until you are done indexing.\nFlush latency:  If you see this metric increasing steadily, it could indicate a problem with slow disks",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: indexing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT mean(\"indexing_index_time_in_millis\") / mean(\"indexing_index_total\") FROM \"elasticsearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY \"node_name\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: flush",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT mean(\"flush_total_time_in_millis\") / mean(\"flush_total\") FROM \"elasticsearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY \"node_name\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: get exists",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"get_exists_time_in_millis\") / mean(\"get_exists_total\") FROM \"elasticsearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY \"node_name\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: search query",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"search_query_time_in_millis\") / mean(\"search_query_total\") FROM \"elasticsearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY \"node_name\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: fetch query",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"search_fetch_time_in_millis\") / mean(\"search_fetch_total\") FROM \"elasticsearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY \"node_name\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rejected requests",
   "type": "graph",
   "description": "The size of each thread pool’s queue represents how many requests are waiting to be served while the node is currently at capacity. The queue allows the node to track and eventually serve these requests instead of discarding them. Thread pool rejections arise once the thread pool’s maximum queue size (which varies based on the type of thread pool) is reached.",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "query": "SELECT max(\"bulk_rejected\") AS \"bulk\", max(\"get_rejected\") AS \"get\", max(\"index_rejected\") AS \"index\", max(\"search_rejected\") AS \"search\" FROM \"elasticsearch_thread_pool\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool queues",
   "type": "graph",
   "description": "The size of each thread pool’s queue represents how many requests are waiting to be served while the node is currently at capacity.",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "query": "SELECT max(\"bulk_queue\") AS \"bulk\", max(\"flush_queue\") AS \"flush\", max(\"get_queue\") AS \"get\", max(\"index_queue\") AS \"index\", max(\"refresh_queue\") AS \"refresh\", max(\"search_queue\") AS \"search\" FROM \"elasticsearch_thread_pool\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}