{
 "title": "ElasticSearch cluster",
 "panels": [
  {
   "title": "Cluster status",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "status_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Nodes status",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "UP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"number_of_nodes\") FROM \"elasticsearch_cluster_health\" WHERE $timeFilter AND \"project_name\" =~ /^$project$/ GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DOWN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"total_number_of_nodes\") - min(\"number_of_nodes\") FROM \"elasticsearch_cluster_health\" WHERE $timeFilter AND \"project_name\" =~ /^$project$/ GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "ElasticSearch shards",
 "panels": [
  {
   "title": "Active primary shards",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "active_primary_shards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "active_shards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "initializing_shards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "relocating_shards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "unassigned_shards" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Network metrics",
 "panels": [
  {
   "title": "Open transport connections",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_transport",
     "select": [
      [
       { "params": [ "server_open" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Open http connections",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name.$col",
     "groupBy": [
      { "params": [ "/^$node_name$/" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_http",
     "query": "SELECT max(\"current_open\") as \"open\" FROM \"elasticsearch_http\" WHERE $timeFilter AND node_name =~ /$node_name/ AND \"project_name\" =~ /^$project$/ GROUP BY time($interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "current_open" ], "type": "field" }
      ],
      [
       { "params": [ "total_opened" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transport size",
   "type": "graph",
   "description": "The Rx(receiving) and Tx(transmitting) package size",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: rx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_transport",
     "query": "SELECT non_negative_derivative(\"rx_size_in_bytes\", 1s) FROM \"elasticsearch_transport\" WHERE \"node_name\" =~ /^$node_name$/ AND $timeFilter GROUP BY time($interval), \"node_name\", fill(none)",
     "select": [
      [
       { "params": [ "rx_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "$tag_node_name: tx",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_transport",
     "query": "SELECT non_negative_derivative(\"rx_size_in_bytes\", 1s) FROM \"elasticsearch_transport\" WHERE \"node_name\" =~ /^$node_name$/ AND $timeFilter GROUP BY time($interval), \"node_name\", fill(none)",
     "select": [
      [
       { "params": [ "tx_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "JVM heap and GC metrics",
 "panels": [
  {
   "title": "JVM heap usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "mem_heap_used_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_heap_max_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM heap usage percent",
   "type": "graph",
   "description": "Elasticsearch is set up to initiate garbage collections whenever JVM heap usage hits 75 percent. As shown above, it may be useful to monitor which nodes exhibit high heap usage, and set up an alert to find out if any node is consistently using over 85 percent of heap memory; this indicates that the rate of garbage collection isn’t keeping up with the rate of garbage creation. To address this problem, you can either increase your heap size (as long as it remains below the recommended guidelines stated above), or scale out the cluster by adding more nodes.",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "SELECT mean(\"mem_heap_used_percent\")  FROM \"elasticsearch_jvm\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval), node_name, *",
     "select": [
      [
       { "params": [ "mem_heap_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM non heap usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "mem_non_heap_used_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "description": "Because garbage collection uses resources (in order to free up resources!), you should keep an eye on its frequency and duration to see if you need to adjust the heap size. Setting the heap too large can result in long garbage collection times; these excessive pauses are dangerous because they can lead your cluster to mistakenly register your node as having dropped off the grid ( Because the master node checks the status of every other node every 30 seconds, if any node’s garbage collection time exceed 30 seconds, it will lead the master to believe that the node has failed).",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       {
        "params": [
         "gc_collectors_old_collection_time_in_millis"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "old" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "gc_collectors_young_collection_time_in_millis"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "young" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Memory metrics",
 "panels": [
  {
   "title": "OS memory usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name used",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$node_name$*/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "pod" }
     ]
    },
    {
     "alias": "$tag_pod_name total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/limit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$node_name$*/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "pod" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Disk metrics",
 "panels": [
  {
   "title": "Disk usage in percent",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host] used",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_fs",
     "query": "SELECT 100*(mean(\"total_total_in_bytes\") - mean(\"total_free_in_bytes\"))/ mean(\"total_total_in_bytes\") FROM \"elasticsearch_fs\" WHERE \"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY \"node_name\" ,\"node_host\", time($interval)",
     "select": [
      [
       { "params": [ "total_available_in_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host] total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "node_host" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_fs",
     "query": "SELECT mean(\"total_total_in_bytes\") FROM \"elasticsearch_fs\" WHERE \"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY time($interval), \"node_name\", \"node_host\"",
     "select": [
      [
       { "params": [ "total_total_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    },
    {
     "alias": "$tag_node_name [$tag_node_host] used",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_fs",
     "query": "SELECT mean(\"total_total_in_bytes\") -mean( \"total_available_in_bytes\") FROM \"elasticsearch_fs\" WHERE \"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY  time($interval), \"node_name\", \"node_host\"",
     "select": [
      [
       { "params": [ "total_available_in_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O operations",
   "type": "graph",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host] $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "node_host" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_fs",
     "query": "SELECT non_negative_derivative(mean(\"io_stats_total_read_operations\"), 1s) AS \"read\", non_negative_derivative(mean(\"io_stats_total_write_operations\"), 1s) AS \"write\" FROM \"elasticsearch_fs\" WHERE \"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY time($interval), \"node_name\", \"node_host\"",
     "select": [
      [
       { "params": [ "io_stats_total_read_operations" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O usage",
   "type": "graph",
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host] $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"io_stats_total_read_kilobytes\"), 1s) AS \"read\", non_negative_derivative(mean(\"io_stats_total_write_kilobytes\"), 1s) AS \"write\" FROM \"elasticsearch_fs\" WHERE \"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY time($interval), \"node_name\", \"node_host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "CPU metrics",
 "panels": [
  {
   "title": "CPU load average (5 min)",
   "type": "graph",
   "description": "Five-minute load average on the system",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "node_host" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_os",
     "select": [
      [
       { "params": [ "cpu_load_average_5m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU load in percent",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name [$tag_node_host]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "node_host" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_process",
     "query": "SELECT mean(\"cpu_percent\")  FROM \"elasticsearch_process\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU load by pod",
   "type": "graph",
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE \"pod_name\" =~ /^$node_name$*/ AND \"type\" = 'pod' AND $timeFilter GROUP BY time($interval), \"pod_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$node_name$*/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "pod" }
     ]
    },
    {
     "alias": "$tag_pod_name total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE \"pod_name\" =~ /^$node_name$*/ AND \"type\" = 'pod' AND $timeFilter GROUP BY time($interval), \"pod_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$node_name$*/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "pod" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Indices statistics",
 "panels": [
  {
   "title": "Indices total operations",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT  mean(flush_total) as \"flush\", mean(get_exists_total) as \"get-exists\", mean(get_missing_total) as \"get-missing\", mean(get_total) as \"get\", mean(indexing_delete_total) as \"indexing-delete\", mean(indexing_index_total) as \"indexing-index\", mean(indexing_noop_update_total) as \"indexing-noop-update\", mean(merges_total) as \"merges\", mean(percolate_total) as \"percolate\", mean(refresh_total) as \"refresh\", mean(search_fetch_total) as \"search-fetch\", mean(search_query_total) as \"search-query\", mean(search_scroll_total) as \"search-scroll\", mean(suggest_total) as \"suggest\", mean(warmer_total) as \"warmer\"  FROM \"elasticsearch_indices\" WHERE node_name =~ /$node_name/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "get_total" ], "type": "field" }
      ],
      [
       { "params": [ "flush_total" ], "type": "field" }
      ],
      [
       { "params": [ "get_exists_total" ], "type": "field" }
      ],
      [
       { "params": [ "get_missing_total" ], "type": "field" }
      ],
      [
       { "params": [ "indexing_delete_total" ], "type": "field" }
      ],
      [
       { "params": [ "indexing_index_total" ], "type": "field" }
      ],
      [
       { "params": [ "merges_total" ], "type": "field" }
      ],
      [
       { "params": [ "indexing_noop_update_total" ], "type": "field" }
      ],
      [
       { "params": [ "percolate_total" ], "type": "field" }
      ],
      [
       { "params": [ "refresh_total" ], "type": "field" }
      ],
      [
       { "params": [ "search_fetch_total" ], "type": "field" }
      ],
      [
       { "params": [ "search_query_total" ], "type": "field" }
      ],
      [
       { "params": [ "suggest_total" ], "type": "field" }
      ],
      [
       { "params": [ "search_scroll_total" ], "type": "field" }
      ],
      [
       { "params": [ "warmer_total" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices time operations",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(merges_total_time_in_millis) AS \"merges-total\",mean(flush_total_time_in_millis) AS \"flush-total\",mean(get_exists_time_in_millis) AS \"get-exists\",mean(get_missing_time_in_millis) AS \"get-missing\",mean(get_time_in_millis) AS \"get\",mean(indexing_delete_time_in_millis) AS \"indexing-delete\",mean(indexing_index_time_in_millis) AS \"indexing-index\",mean(indexing_throttle_time_in_millis) AS \"indexing-throttle\",mean(merges_total_stopped_time_in_millis) AS \"merges-total-stopped\",mean(merges_total_throttled_time_in_millis) AS \"merges-total-throttled\",mean(merges_total_time_in_millis) AS \"merges-total\",mean(percolate_time_in_millis) AS \"percolate\",mean(recovery_throttle_time_in_millis) AS \"recovery-throttle\",mean(refresh_total_time_in_millis) AS \"refresh-total\",mean(search_fetch_time_in_millis) AS \"search-fetch\",mean(search_query_time_in_millis) AS \"search-query\",mean(search_scroll_time_in_millis) AS \"search-scroll\",mean(store_throttle_time_in_millis) AS \"store-throttle\",mean(suggest_time_in_millis) AS \"suggest\",mean(warmer_total_time_in_millis) AS \"warmer-total\" FROM \"elasticsearch_indices\" WHERE node_name =~ /$node_name/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices current operations",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "get_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "get" ], "type": "alias" }
      ],
      [
       { "params": [ "indexing_index_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "index" ], "type": "alias" }
      ],
      [
       { "params": [ "search_fetch_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "search fetch" ], "type": "alias" }
      ],
      [
       { "params": [ "search_query_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "search query" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Indices document count",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "document count",
     "groupBy": [
      { "params": [ "cluster_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "select": [
      [
       { "params": [ "docs_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Indices data size",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "indices size",
     "groupBy": [
      { "params": [ "cluster_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "query": "SELECT \"total_available_in_bytes\", \"total_free_in_bytes\" FROM \"elasticsearch_fs\" WHERE $timeFilter GROUP BY \"node_id\"",
     "select": [
      [
       { "params": [ "store_size_in_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Thread pool queues and requests metrics",
 "panels": [
  {
   "title": "Requests latency",
   "type": "graph",
   "description": "If you notice the indexing latency increasing, you may be trying to index too many documents at one time (Elasticsearch’s documentation recommends starting with a bulk indexing size of 5 to 15 megabytes and increasing slowly from there).\nIf you are planning to index a lot of documents and you don’t need the new information to be immediately available for search, you can optimize for indexing performance over search performance by decreasing refresh frequency until you are done indexing.\nFlush latency:  If you see this metric increasing steadily, it could indicate a problem with slow disks",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: indexing",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT mean(\"indexing_index_time_in_millis\")/ mean(\"indexing_index_total\") FROM \"elasticsearch_indices\" WHERE \"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY \"node_name\", time($interval)",
     "select": [
      [
       { "params": [ "indexing_index_time_in_millis" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    },
    {
     "alias": "$tag_node_name: flush",
     "groupBy": [
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT mean(\"flush_total_time_in_millis\")/mean(\"flush_total\") FROM \"elasticsearch_indices\" WHERE \"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY \"node_name\", time($interval)",
     "select": [
      [
       { "params": [ "flush_total_time_in_millis" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    },
    {
     "alias": "$tag_node_name: get exists",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"get_exists_time_in_millis\")/mean(\"get_exists_total\") FROM \"elasticsearch_indices\" WHERE \"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY \"node_name\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: search query",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"search_query_time_in_millis\")/mean(\"search_query_total\") FROM \"elasticsearch_indices\" WHERE \"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY \"node_name\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: fetch query",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"search_fetch_time_in_millis\")/mean(\"search_fetch_total\") FROM \"elasticsearch_indices\" WHERE \"node_name\" =~ /^$node_name$/ AND \"project_name\" =~ /^$project$/ AND $timeFilter GROUP BY \"node_name\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rejected requests",
   "type": "graph",
   "description": "The size of each thread pool’s queue represents how many requests are waiting to be served while the node is currently at capacity. The queue allows the node to track and eventually serve these requests instead of discarding them. Thread pool rejections arise once the thread pool’s maximum queue size (which varies based on the type of thread pool) is reached.",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "bulk_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "bulk" ], "type": "alias" }
      ],
      [
       { "params": [ "get_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "get" ], "type": "alias" }
      ],
      [
       { "params": [ "index_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "index" ], "type": "alias" }
      ],
      [
       { "params": [ "search_rejected" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "search" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread pool queues",
   "type": "graph",
   "description": "The size of each thread pool’s queue represents how many requests are waiting to be served while the node is currently at capacity.",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "bulk_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "bulk" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "flush" ], "type": "alias" }
      ],
      [
       { "params": [ "get_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "get" ], "type": "alias" }
      ],
      [
       { "params": [ "index_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "index" ], "type": "alias" }
      ],
      [
       { "params": [ "refresh_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "refresh" ], "type": "alias" }
      ],
      [
       { "params": [ "search_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "search" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Smoke test",
 "panels": [
  {
   "title": "Smoke test",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "create",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_smoke_test",
     "query": "SELECT last(\"result\") FROM \"elasticsearch_smoke\" WHERE $timeFilter GROUP BY time($__interval), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "create_data" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "delete",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_smoke_test",
     "query": "SELECT last(\"result\") FROM \"elasticsearch_smoke\" WHERE $timeFilter GROUP BY time($__interval), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "delete_data" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "get",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_smoke_test",
     "query": "SELECT last(\"result\") FROM \"elasticsearch_smoke\" WHERE $timeFilter GROUP BY time($__interval), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "get_data" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "update",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_smoke_test",
     "query": "SELECT last(\"result\") FROM \"elasticsearch_smoke\" WHERE $timeFilter GROUP BY time($__interval), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "update_data" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Smoke test timing",
   "type": "graph",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "create",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_smoke_test",
     "query": "SELECT last(\"execution_time\") FROM \"elasticsearch_smoke\" WHERE $timeFilter GROUP BY time($__interval), \"type\"",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "create_data" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "delete",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_smoke_test",
     "query": "SELECT last(\"execution_time\") FROM \"elasticsearch_smoke\" WHERE $timeFilter GROUP BY time($__interval), \"type\"",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "delete_data" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "get",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_smoke_test",
     "query": "SELECT last(\"execution_time\") FROM \"elasticsearch_smoke\" WHERE $timeFilter GROUP BY time($__interval), \"type\"",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "get_data" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "update",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_smoke_test",
     "query": "SELECT last(\"execution_time\") FROM \"elasticsearch_smoke\" WHERE $timeFilter GROUP BY time($__interval), \"type\"",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "update_data" },
      { "condition": "AND", "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  }
 ]
}