apiVersion: 1

datasources:
  - name: 'InfluxDB'
    type: 'influxdb'
    editable: true
    access: 'proxy'
    url: 'http://influxdb:8086'
    is_default: true
    org_id: 1
    database: 'monitoring'
    version: 1
    user: 'influx'
    password: 'influx'
  - name: 'Prometheus'
    type: 'prometheus'
    editable: true
    access: 'proxy'
    url: 'http://prometheus:9090'